/**
 * Hindsight defaults to no change (#98).
 *
 * On one live store the phase reviewed five entrenched memories and revised
 * all five: first person became third, a number was dropped, and a precise
 * fact gained a qualifier nothing in the store contained. The prompt asked
 * what a definition "assumes" or "lacks", and a precise memory is exactly the
 * one a critic can always hedge. Now a concern counts only when the model
 * cites a connected concept or the belief history, and a rewrite is applied
 * only when it keeps everything the old definition committed to.
 */

import { describe, it, expect, vi } from 'vitest';
import { hindsightReview } from './cognition.js';
import { newFSRSState } from './fsrs.js';
import { SqliteCortexStore } from '../stores/sqlite.js';
import type { LLMProvider } from '../core/llm.js';
import type { Memory } from '../core/types.js';

const NAME = 'Interrogation: Gemini Asks Hard Questions';
const OLD =
  "Gave Gemini Pro my profile, quirks, and opinions. Asked it to generate 5 questions I'd struggle to answer honestly. Then I tried to answer them honestly.";
const HEDGED =
  'Interrogation: Gemini Asks Hard Questions — A process where a user provides personal information to an AI model (e.g., Gemini Pro) and attempts to answer questions generated by the AI that are designed to challenge honesty.';
const NEIGHBOUR = 'Honesty under questioning';
const NEIGHBOUR_DEF = 'Answering hard questions honestly is a practice I keep.';

function memory(overrides: Partial<Omit<Memory, 'id'>>): Omit<Memory, 'id'> {
  const now = new Date();
  return {
    name: NAME,
    definition: OLD,
    category: 'insight',
    salience: 0.7,
    confidence: 0.85,
    access_count: 12,
    created_at: now,
    updated_at: now,
    last_accessed: now,
    source_files: [],
    embedding: [1, 0, 0],
    tags: [],
    fsrs: { ...newFSRSState(), state: 'review', stability: 40, reps: 6, lapses: 0 },
    ...overrides,
  };
}

function llmReturning(json: unknown): LLMProvider & { generateJSON: ReturnType<typeof vi.fn> } {
  return {
    name: 'fake',
    modelId: 'fake',
    generate: vi.fn(async () => ''),
    generateJSON: vi.fn(async () => json),
  } as unknown as LLMProvider & { generateJSON: ReturnType<typeof vi.fn> };
}

async function seed(store: SqliteCortexStore, withNeighbour = true): Promise<string> {
  const id = await store.putMemory(memory({}));
  if (withNeighbour) {
    // Not entrenched itself, so only the target is a candidate.
    const neighbourId = await store.putMemory(memory({
      name: NEIGHBOUR, definition: NEIGHBOUR_DEF, embedding: [0, 1, 0], fsrs: newFSRSState(),
    }));
    await store.putEdge({
      source_id: id, target_id: neighbourId, relation: 'related', weight: 0.6,
      evidence: 'both are about answering honestly', created_at: new Date(),
    });
  }
  return id;
}

describe('hindsightReview', () => {
  it('leaves a memory alone when the review cites nothing in the store', async () => {
    const store = new SqliteCortexStore(':memory:');
    const id = await seed(store);
    const llm = llmReturning({
      concern: 'The definition lacks contextual depth and may not capture the full range of the practice.',
      cited: null,
      confidence_penalty: 0.15,
      revised_definition: HEDGED,
      reason: 'lacks contextual depth',
    });

    const result = await hindsightReview(store, llm, {});

    expect(result).toEqual({ reviewed: 1, revised: 0, declined: 0 });
    const after = await store.getMemory(id);
    expect(after?.definition).toBe(OLD);
    expect(after?.confidence).toBe(0.85);
    expect(await store.getBeliefHistory(id)).toEqual([]);
    expect(await store.getSignals()).toEqual([]);
  });

  it('declines a cited rewrite that hedges, drops the number or shifts to third person', async () => {
    const store = new SqliteCortexStore(':memory:');
    const id = await seed(store);
    const llm = llmReturning({
      concern: 'Overstated relative to the connected concept.',
      cited: NEIGHBOUR,
      confidence_penalty: 0.1,
      revised_definition: HEDGED,
      reason: 'assumes universal applicability',
    });
    const errors = vi.spyOn(console, 'error').mockImplementation(() => {});

    const result = await hindsightReview(store, llm, {});

    expect(result).toEqual({ reviewed: 1, revised: 1, declined: 1 });
    const after = await store.getMemory(id);
    expect(after?.definition).toBe(OLD);
    expect(after?.confidence).toBeCloseTo(0.75, 5);
    expect(await store.getBeliefHistory(id)).toEqual([]);
    expect(errors.mock.calls.some((c) => String(c[0]).includes('Declined rewrite'))).toBe(true);
    errors.mockRestore();
  });

  it('applies a cited rewrite that keeps every specific and the voice', async () => {
    const store = new SqliteCortexStore(':memory:');
    const id = await seed(store);
    const next = `${OLD} Answering them honestly is a practice I keep.`;
    const llm = llmReturning({
      concern: null,
      cited: NEIGHBOUR,
      confidence_penalty: 0,
      revised_definition: next,
      reason: `"${NEIGHBOUR}" shows the practice continued`,
    });

    const result = await hindsightReview(store, llm, {});

    expect(result).toEqual({ reviewed: 1, revised: 1, declined: 0 });
    expect((await store.getMemory(id))?.definition).toBe(next);
    const history = await store.getBeliefHistory(id);
    expect(history).toHaveLength(1);
    expect(history[0]?.old_definition).toBe(OLD);
    expect(history[0]?.reason).toMatch(/^\[hindsight\]/);
  });

  it('treats a citation that names nothing connected as no citation', async () => {
    const store = new SqliteCortexStore(':memory:');
    const id = await seed(store, false);
    const llm = llmReturning({
      concern: 'Contradicted by later evidence.',
      cited: 'A memory that does not exist',
      confidence_penalty: 0.2,
      revised_definition: `${OLD} Later I stopped.`,
      reason: 'history',
    });

    const result = await hindsightReview(store, llm, {});

    expect(result).toEqual({ reviewed: 1, revised: 0, declined: 0 });
    expect((await store.getMemory(id))?.definition).toBe(OLD);
    expect((await store.getMemory(id))?.confidence).toBe(0.85);
  });

  it('does not review a memory that is not entrenched', async () => {
    const store = new SqliteCortexStore(':memory:');
    await store.putMemory(memory({ fsrs: newFSRSState() }));
    const llm = llmReturning({ concern: null, cited: null, confidence_penalty: 0, revised_definition: null, reason: '' });

    const result = await hindsightReview(store, llm, {});

    expect(result).toEqual({ reviewed: 0, revised: 0, declined: 0 });
    expect(llm.generateJSON).not.toHaveBeenCalled();
  });
});
