/**
 * Rewrite guard (#98). The fixtures are the three rows the 2026-09-13 attended
 * dream damaged and the post-run diff caught by hand.
 */

import { describe, it, expect } from 'vitest';
import { checkRewrite } from './rewrite-guard.js';

const GEMINI_OLD =
  "Gave Gemini Pro my profile, quirks, and opinions. Asked it to generate 5 questions I'd struggle to answer honestly. Then I tried to answer them honestly.";
const GEMINI_HEDGED =
  'Interrogation: Gemini Asks Hard Questions — A process where a user provides personal information to an AI model (e.g., Gemini Pro) and attempts to answer questions generated by the AI that are designed to challenge honesty. This practice is used as a tool for self-reflection.';

const MCP_OLD =
  'Claude Code interpolates ${VAR} in .mcp.json env blocks since v2.1.64, so a key can live in the environment and never in the file.';

describe('checkRewrite', () => {
  it('catches the name-as-opener, dropped number and person shift together', () => {
    const r = checkRewrite({ name: 'Interrogation: Gemini Asks Hard Questions', old: GEMINI_OLD, next: GEMINI_HEDGED });
    expect(r.ok).toBe(false);
    expect(r.reasons).toEqual(expect.arrayContaining([
      'name restated as opener',
      'dropped numbers: 5',
      'first person became third person',
    ]));
  });

  it('catches an invented qualifier on a precise fact', () => {
    const r = checkRewrite({
      name: 'Env interpolation in .mcp.json',
      old: MCP_OLD,
      next: `${MCP_OLD.slice(0, -1)}, but only in configurations where the underlying system or runtime environment explicitly supports such interpolation.`,
    });
    expect(r.ok).toBe(false);
    expect(r.reasons).toEqual(['added hedges: but only']);
  });

  it('catches a hedge that reframes a value as a construct', () => {
    const old = 'My family taught me that resilience is built by staying, not by leaving.';
    const r = checkRewrite({
      name: 'Resilience is built by staying',
      old,
      next: 'My family taught me that resilience is built by staying, not by leaving, acknowledging the narrative as a construct.',
    });
    expect(r.ok).toBe(false);
    expect(r.reasons.join(' ')).toContain('added hedges');
  });

  it('catches dropped quotations and boilerplate openers', () => {
    const old = 'Virgil said "you\'re the best, remember that" after the shipping session on 2026-09-10.';
    const r = checkRewrite({
      name: 'Appreciation',
      old,
      next: 'This concept refers to praise Virgil gave after a shipping session on 2026-09-10.',
    });
    expect(r.reasons).toEqual(expect.arrayContaining(['boilerplate opener', 'dropped quotations: 1']));
  });

  it('accepts a rewrite that keeps every specific and draws only on the evidence', () => {
    const r = checkRewrite({
      name: 'Interrogation: Gemini Asks Hard Questions',
      old: GEMINI_OLD,
      next: `${GEMINI_OLD} Answering them honestly is a practice I keep.`,
      evidence: ['Answering hard questions honestly is a practice I keep.'],
    });
    expect(r).toEqual({ ok: true, reasons: [] });
  });

  it('allows an entity or hedge that the evidence itself contains', () => {
    const r = checkRewrite({
      name: 'Refine fallback',
      old: 'Refine rewrote 21 memories in one run because it fell back to edge evidence.',
      next: 'Refine rewrote 21 memories in one run because it fell back to edge evidence; since PR #87 it only rewrites a memory that gained direct evidence, depending on the run.',
      evidence: ['PR #87 made refine rewrite only memories with direct evidence, depending on the run.'],
    });
    expect(r).toEqual({ ok: true, reasons: [] });
  });

  it('does not flag a definition that already opened with its own name', () => {
    const r = checkRewrite({
      name: 'The sky is blue',
      old: 'The sky is blue on clear days.',
      next: 'The sky is blue on clear days and grey under cloud.',
    });
    expect(r).toEqual({ ok: true, reasons: [] });
  });
});
